/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ifpr.lp.covid.tds.view;

import br.ifpr.lp.covid.tds.controller.CovidController;
import br.ifpr.lp.covid.tds.controller.LoginController;
import br.ifpr.lp.covid.tds.controller.UsuarioSessao;
import static br.ifpr.lp.covid.tds.controller.UsuarioSessao.getUsuarioLogado;
import br.ifpr.lp.covid.tds.model.DadosPais;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Locale;

/**
 *
 * @author Renato
 */
public class DadosCovid extends javax.swing.JFrame {
    
    Locale localeBR = new Locale("pt","BR");
    NumberFormat numberFormat = NumberFormat.getNumberInstance(localeBR);
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    
    CovidController covidController = new CovidController();
    LoginController loginController = new LoginController();
    /**
     * Creates new form DadosCovid
     */
    public DadosCovid() {
        initComponents();
        
        botoesPorPermissao();
        
        DadosPais dados = covidController.getDadosBrasil();
        
        if (dados != null){
            
            lbData.setText(dados.getDataAtualizacao() != null ? sdf.format(dados.getDataAtualizacao()) : "");
            lbNovasMortes.setText(numberFormat.format(dados.getNovasMortes()));
            lbNovosCasos.setText(numberFormat.format(dados.getNovosCasos()));
            lbNovosRecuperados.setText(numberFormat.format(dados.getNovosRecuperados()));
            lbPais.setText(dados.getPais());
            lbTotalCasos.setText(numberFormat.format(dados.getTotalDeCasos()));
            lbTotalMortes.setText(numberFormat.format(dados.getTotalMorte()));
            lbTotalRecuperados.setText(numberFormat.format(dados.getTotalRecuperados()));

        }
        
    }

    private void botoesPorPermissao() {
        if (getUsuarioLogado() == null || !getUsuarioLogado().getPerfil().equals("admin")){
            btnNovoUsuario.setVisible(false);
            btnListar.setVisible(false);
        }else{
            btnNovoUsuario.setVisible(true);
            btnListar.setVisible(true);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAcoes = new javax.swing.JPanel();
        btnNovoUsuario = new javax.swing.JButton();
        btnListar = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        btnLogoff = new javax.swing.JButton();
        pnlDados = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbPais = new javax.swing.JLabel();
        lbData = new javax.swing.JLabel();
        lbNovosCasos = new javax.swing.JLabel();
        lbNovasMortes = new javax.swing.JLabel();
        lbNovosRecuperados = new javax.swing.JLabel();
        lbTotalCasos = new javax.swing.JLabel();
        lbTotalMortes = new javax.swing.JLabel();
        lbTotalRecuperados = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        pnlAcoes.setBackground(new java.awt.Color(51, 51, 51));
        pnlAcoes.setPreferredSize(new java.awt.Dimension(590, 40));
        pnlAcoes.setLayout(new java.awt.GridLayout(1, 4, 5, 5));

        btnNovoUsuario.setBackground(new java.awt.Color(0, 153, 153));
        btnNovoUsuario.setForeground(new java.awt.Color(255, 255, 255));
        btnNovoUsuario.setText("Novo Usuário");
        btnNovoUsuario.setBorder(null);
        btnNovoUsuario.setPreferredSize(new java.awt.Dimension(70, 35));
        btnNovoUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                novoUsuarioAction(evt);
            }
        });
        pnlAcoes.add(btnNovoUsuario);

        btnListar.setBackground(new java.awt.Color(0, 153, 153));
        btnListar.setForeground(new java.awt.Color(255, 255, 255));
        btnListar.setText("Listar");
        btnListar.setBorder(null);
        btnListar.setPreferredSize(new java.awt.Dimension(70, 35));
        btnListar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                listarUsuariosAction(evt);
            }
        });
        pnlAcoes.add(btnListar);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 120, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        pnlAcoes.add(jPanel3);

        btnLogoff.setBackground(new java.awt.Color(102, 102, 102));
        btnLogoff.setForeground(new java.awt.Color(255, 255, 255));
        btnLogoff.setText("Logoff");
        btnLogoff.setBorder(null);
        btnLogoff.setPreferredSize(new java.awt.Dimension(70, 35));
        btnLogoff.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutAction(evt);
            }
        });
        pnlAcoes.add(btnLogoff);

        getContentPane().add(pnlAcoes, java.awt.BorderLayout.PAGE_START);

        pnlDados.setBackground(new java.awt.Color(51, 51, 51));
        pnlDados.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Covid ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N
        pnlDados.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("País:");
        pnlDados.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 24, 166, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Novas Mortes");
        pnlDados.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 125, -1, -1));

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Novos Casos");
        pnlDados.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 125, 166, -1));

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Data:");
        pnlDados.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 24, -1, -1));

        lbPais.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbPais.setForeground(new java.awt.Color(255, 255, 255));
        lbPais.setText("jLabel9");
        pnlDados.add(lbPais, new org.netbeans.lib.awtextra.AbsoluteConstraints(11, 46, -1, -1));

        lbData.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbData.setForeground(new java.awt.Color(255, 255, 255));
        lbData.setText("jLabel9");
        pnlDados.add(lbData, new org.netbeans.lib.awtextra.AbsoluteConstraints(183, 46, -1, -1));

        lbNovosCasos.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbNovosCasos.setForeground(new java.awt.Color(204, 0, 0));
        lbNovosCasos.setText("jLabel9");
        pnlDados.add(lbNovosCasos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 150, -1, -1));

        lbNovasMortes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbNovasMortes.setForeground(new java.awt.Color(204, 0, 0));
        lbNovasMortes.setText("jLabel9");
        pnlDados.add(lbNovasMortes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 150, -1, -1));

        lbNovosRecuperados.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbNovosRecuperados.setForeground(new java.awt.Color(0, 204, 51));
        lbNovosRecuperados.setText("jLabel9");
        pnlDados.add(lbNovosRecuperados, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 150, -1, -1));

        lbTotalCasos.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbTotalCasos.setForeground(new java.awt.Color(204, 0, 0));
        lbTotalCasos.setText("jLabel9");
        pnlDados.add(lbTotalCasos, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        lbTotalMortes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbTotalMortes.setForeground(new java.awt.Color(204, 0, 0));
        lbTotalMortes.setText("jLabel9");
        pnlDados.add(lbTotalMortes, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 240, -1, -1));

        lbTotalRecuperados.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbTotalRecuperados.setForeground(new java.awt.Color(0, 204, 51));
        lbTotalRecuperados.setText("jLabel9");
        pnlDados.add(lbTotalRecuperados, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Novo Recuperados");
        pnlDados.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(322, 125, -1, -1));

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total de Recuperados");
        pnlDados.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 210, -1, -1));

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total de Casos");
        pnlDados.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 210, 166, -1));

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total de Mortes");
        pnlDados.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, -1));

        getContentPane().add(pnlDados, java.awt.BorderLayout.CENTER);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void novoUsuarioAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_novoUsuarioAction
        
        CadUsuario cad = new CadUsuario();
        cad.setLocationRelativeTo(null);
        cad.setVisible(true);
        
    }//GEN-LAST:event_novoUsuarioAction

    private void logoutAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutAction
        Login login = new Login();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        
        loginController.logout();
        
        this.dispose();
       
    }//GEN-LAST:event_logoutAction

    private void listarUsuariosAction(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_listarUsuariosAction
        ListUsuario lista = new ListUsuario();
        lista.setLocationRelativeTo(null);
        lista.setVisible(true);
    }//GEN-LAST:event_listarUsuariosAction

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnListar;
    private javax.swing.JButton btnLogoff;
    private javax.swing.JButton btnNovoUsuario;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbNovasMortes;
    private javax.swing.JLabel lbNovosCasos;
    private javax.swing.JLabel lbNovosRecuperados;
    private javax.swing.JLabel lbPais;
    private javax.swing.JLabel lbTotalCasos;
    private javax.swing.JLabel lbTotalMortes;
    private javax.swing.JLabel lbTotalRecuperados;
    private javax.swing.JPanel pnlAcoes;
    private javax.swing.JPanel pnlDados;
    // End of variables declaration//GEN-END:variables
}
