/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.ifpr.lp.covid.tds.main;

import br.ifpr.lp.covid.tds.model.DadosPais;
import br.ifpr.lp.covid.tds.service.CovidService;
import java.text.NumberFormat;
import java.text.SimpleDateFormat;
import java.util.Locale;

/**
 *
 * @author Renato
 */
public class DadosCovid extends javax.swing.JFrame {
    
    Locale localeBR = new Locale("pt","BR");
    NumberFormat numberFormat = NumberFormat.getNumberInstance(localeBR);
    SimpleDateFormat sdf = new SimpleDateFormat("dd-MM-yyyy");
    /**
     * Creates new form DadosCovid
     */
    public DadosCovid() {
        initComponents();
        
        CovidService service = new CovidService();
        DadosPais dados =  service.getDadosCovidBrasil();
        
        if (dados != null){
            
            lbData.setText(dados.getDataAtualizacao() != null ? sdf.format(dados.getDataAtualizacao()) : "");
            lbNovasMortes.setText(numberFormat.format(dados.getNovasMortes()));
            lbNovosCasos.setText(numberFormat.format(dados.getNovosCasos()));
            lbNovosRecuperados.setText(numberFormat.format(dados.getNovosRecuperados()));
            lbPais.setText(dados.getPais());
            lbTotalCasos.setText(numberFormat.format(dados.getTotalDeCasos()));
            lbTotalMortes.setText(numberFormat.format(dados.getTotalMorte()));
            lbTotalRecuperados.setText(numberFormat.format(dados.getTotalRecuperados()));

        }
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        lbPais = new javax.swing.JLabel();
        lbData = new javax.swing.JLabel();
        lbNovosCasos = new javax.swing.JLabel();
        lbNovasMortes = new javax.swing.JLabel();
        lbNovosRecuperados = new javax.swing.JLabel();
        lbTotalCasos = new javax.swing.JLabel();
        lbTotalMortes = new javax.swing.JLabel();
        lbTotalRecuperados = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(51, 51, 51));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Dados Covid ", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Dialog", 1, 12), new java.awt.Color(255, 255, 255))); // NOI18N

        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("País:");

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Novas Mortes");

        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Novos Casos");

        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Data:");

        lbPais.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbPais.setForeground(new java.awt.Color(255, 255, 255));
        lbPais.setText("jLabel9");

        lbData.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbData.setForeground(new java.awt.Color(255, 255, 255));
        lbData.setText("jLabel9");

        lbNovosCasos.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbNovosCasos.setForeground(new java.awt.Color(204, 0, 0));
        lbNovosCasos.setText("jLabel9");

        lbNovasMortes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbNovasMortes.setForeground(new java.awt.Color(204, 0, 0));
        lbNovasMortes.setText("jLabel9");

        lbNovosRecuperados.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbNovosRecuperados.setForeground(new java.awt.Color(0, 204, 51));
        lbNovosRecuperados.setText("jLabel9");

        lbTotalCasos.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbTotalCasos.setForeground(new java.awt.Color(204, 0, 0));
        lbTotalCasos.setText("jLabel9");

        lbTotalMortes.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbTotalMortes.setForeground(new java.awt.Color(204, 0, 0));
        lbTotalMortes.setText("jLabel9");

        lbTotalRecuperados.setFont(new java.awt.Font("Dialog", 1, 24)); // NOI18N
        lbTotalRecuperados.setForeground(new java.awt.Color(0, 204, 51));
        lbTotalRecuperados.setText("jLabel9");

        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Novo Recuperados");

        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Total de Recuperados");

        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Total de Casos");

        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Total de Mortes");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbPais)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lbNovosCasos)
                                            .addComponent(lbTotalCasos))
                                        .addGap(89, 89, 89))
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addComponent(jLabel1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGap(6, 6, 6)))
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbNovasMortes)
                                    .addComponent(lbData)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel2)
                                    .addComponent(lbTotalMortes)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel5)))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(lbNovosRecuperados)
                            .addComponent(jLabel4)
                            .addComponent(lbTotalRecuperados))))
                .addContainerGap(137, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbPais)
                    .addComponent(lbData))
                .addGap(47, 47, 47)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel2)
                        .addComponent(jLabel3))
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbNovosCasos)
                    .addComponent(lbNovasMortes)
                    .addComponent(lbNovosRecuperados))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel6)
                            .addComponent(jLabel5))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbTotalRecuperados)
                            .addComponent(lbTotalMortes))
                        .addGap(90, 90, 90))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(lbTotalCasos)
                        .addContainerGap())))
        );

        getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBackground(new java.awt.Color(51, 51, 51));
        jPanel2.setPreferredSize(new java.awt.Dimension(590, 50));

        jButton1.setBackground(new java.awt.Color(204, 204, 204));
        jButton1.setForeground(new java.awt.Color(0, 0, 0));
        jButton1.setText("Novo Usuário");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(204, 204, 204));
        jButton2.setForeground(new java.awt.Color(0, 0, 0));
        jButton2.setText("Logoff");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 314, Short.MAX_VALUE)
                .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton2, javax.swing.GroupLayout.DEFAULT_SIZE, 38, Short.MAX_VALUE))
                .addContainerGap())
        );

        getContentPane().add(jPanel2, java.awt.BorderLayout.PAGE_START);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
        CadUsuario cad = new CadUsuario();
        cad.setLocationRelativeTo(null);
        cad.setVisible(true);
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Login login = new Login();
        login.setLocationRelativeTo(null);
        login.setVisible(true);
        
        this.dispose();
       
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lbData;
    private javax.swing.JLabel lbNovasMortes;
    private javax.swing.JLabel lbNovosCasos;
    private javax.swing.JLabel lbNovosRecuperados;
    private javax.swing.JLabel lbPais;
    private javax.swing.JLabel lbTotalCasos;
    private javax.swing.JLabel lbTotalMortes;
    private javax.swing.JLabel lbTotalRecuperados;
    // End of variables declaration//GEN-END:variables
}
